// <auto-generated />
using FaunaFlor.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaunaFlor.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20230803193838_adicaoDescricaoMaisExtensa")]
    partial class adicaoDescricaoMaisExtensa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalHabitat", b =>
                {
                    b.Property<int>("AnimaisAnimalId")
                        .HasColumnType("int");

                    b.Property<int>("HabitatsHabitatId")
                        .HasColumnType("int");

                    b.HasKey("AnimaisAnimalId", "HabitatsHabitatId");

                    b.HasIndex("HabitatsHabitatId");

                    b.ToTable("AnimalHabitat");
                });

            modelBuilder.Entity("FaunaFlor.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("DescricaoPrincipal")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("longtext");

                    b.Property<int>("DietaId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AnimalId");

                    b.HasIndex("DietaId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("FaunaFlor.Models.Dieta", b =>
                {
                    b.Property<int>("DietaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DietaId");

                    b.ToTable("Dietas");
                });

            modelBuilder.Entity("FaunaFlor.Models.Habitat", b =>
                {
                    b.Property<int>("HabitatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("DescricaoPrincipal")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("longtext");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("HabitatId");

                    b.ToTable("Habitats");
                });

            modelBuilder.Entity("AnimalHabitat", b =>
                {
                    b.HasOne("FaunaFlor.Models.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimaisAnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaunaFlor.Models.Habitat", null)
                        .WithMany()
                        .HasForeignKey("HabitatsHabitatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FaunaFlor.Models.Animal", b =>
                {
                    b.HasOne("FaunaFlor.Models.Dieta", "Dieta")
                        .WithMany("Animais")
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("FaunaFlor.Models.Dieta", b =>
                {
                    b.Navigation("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
